In [ ]:
#установка библиотеки и подключение всех необходимых библиотек
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

In [ ]:
#Взяла полученный список векторов векторизированный с помощью метода TF-IDF
db = pd.read_csv('/content/TF-IDF.csv', sep = ',')
db.head()

10   11   12   15   17   18   20   23   30   36  ...  яковливич  ялта  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...        0.0   0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...        0.0   0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...        0.0   0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...        0.0   0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...        0.0   0.0   

   январь  яндекс  ярмарка  ясно  яхта  яхточка  ёлка  Sentiment digits  
0     0.0     0.0      0.0   0.0   0.0      0.0   0.0                 0  
1     0.0     0.0      0.0   0.0   0.0      0.0   0.0                 0  
2     0.0     0.0      0.0   0.0   0.0      0.0   0.0                 0  
3     0.0     0.0      0.0   0.0   0.0      0.0   0.0                 0  
4     0.0     0.0      0.0   0.0   0.0      0.0   0.0                 0  

[5 rows x 3127 columns]

In [ ]:
#Разделить данные на обучающее и тестовое множество 80% на 20%
X_train, X_test, y_train, y_test = train_test_split(
    db.drop(['Sentiment digits'], axis = 1),
    db['Sentiment digits'],
    test_size=0.2,
    shuffle = True,
    random_state=42,
    stratify = None)

In [ ]:
#1.Обучение логистической регрессией
reg = LogisticRegression(
        penalty = 'l2', #{‘l1’, ‘l2’, ‘elasticnet’, None}, default=’l2’
        C = 0.2, #float, default=1.0
        class_weight = 'balanced', #dict or ‘balanced’, default=None
        random_state = 42,
        max_iter = 100, #int, default=100
        n_jobs = -1, #int, default=None
)

#предобученный классификатор
reg_pretrained = reg.fit(X_train, y_train)

y_predict_logreg = reg_pretrained.predict(X_test)
y_predict_logreg

array([0, 1, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 0, 1,
       2, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 1, 1, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 1,
       2, 1, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0])

In [ ]:
#2.Обучение методом опорных векторов
support_vectors = LinearSVC(
        penalty = 'l2', #{‘l1’, ‘l2’}, default=’l2’
        C = 0.2, #float, default=1.0
        class_weight = 'balanced', #dict or ‘balanced’, default=None
        random_state = 42,
        max_iter = 2000 #int, default=1000
)

#предобученный классификатор
support_vectors_pretrained = support_vectors.fit(X_train, y_train)

y_predict_support_vectors = support_vectors_pretrained.predict(X_test)
y_predict_support_vectors

array([0, 1, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 1,
       2, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 1, 1, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0,
       2, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 1, 0, 2, 1, 1, 1, 0, 2, 0])

In [ ]:
#3.Обучение методом деревья решений
tree =  DecisionTreeClassifier(
        criterion = 'entropy', #{“gini”, “entropy”, “log_loss”}, default=”gini”
        splitter = 'best', #{“best”, “random”}, default=”best”
        max_depth = 200, #int, default=None
        class_weight = 'balanced', #dict or ‘balanced’, default=None
        random_state = 42
)

#предобученный классификатор
tree_pretrained = tree.fit(X_train, y_train)

y_predict_tree = tree_pretrained.predict(X_test)
y_predict_tree

array([0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       2, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 1, 2,
       2, 1, 0, 2, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 2, 1, 0, 2, 0, 1, 1, 1, 0, 0])

In [ ]:
#4.Обучение методом случайный лес
random_forest =  DecisionTreeClassifier(
        criterion = 'entropy', #{“gini”, “entropy”, “log_loss”}, default=”gini”
        splitter = 'best', #{“best”, “random”}, default=”best”
        max_depth = 200, #int, default=None
        class_weight = 'balanced', #dict or ‘balanced’, default=None
        random_state = 42
)

#предобученный классификатор
random_forest_pretrained = random_forest.fit(X_train, y_train)

y_predict_random_forest = random_forest_pretrained.predict(X_test)
y_predict_random_forest

array([0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       2, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 1, 2,
       2, 1, 0, 2, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 2, 1, 0, 2, 0, 1, 1, 1, 0, 0])

In [ ]:
#5.Обучение методом K-ближайших соседей
knn =  DecisionTreeClassifier(
        criterion = 'entropy', #{“gini”, “entropy”, “log_loss”}, default=”gini”
        splitter = 'best', #{“best”, “random”}, default=”best”
        max_depth = 200, #int, default=None
        class_weight = 'balanced', #dict or ‘balanced’, default=None
        random_state = 42
)

#предобученный классификатор
knn_pretrained = knn.fit(X_train, y_train)

y_predict_knn = knn_pretrained.predict(X_test)
y_predict_knn

array([0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       2, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 1, 2,
       2, 1, 0, 2, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 2, 1, 0, 2, 0, 1, 1, 1, 0, 0])

In [ ]:
#оценка метода логистической регрессии
print(classification_report(y_test, y_predict_logreg, digits = 4))

              precision    recall  f1-score   support

           0     0.8986    0.9538    0.9254        65
           1     0.8846    0.7931    0.8364        29
           2     1.0000    0.9231    0.9600        13

    accuracy                         0.9065       107
   macro avg     0.9277    0.8900    0.9072       107
weighted avg     0.9071    0.9065    0.9055       107



In [ ]:
#оценка метода опорных векторов
print(classification_report(y_test, y_predict_support_vectors, digits = 4))

              precision    recall  f1-score   support

           0     0.8784    1.0000    0.9353        65
           1     1.0000    0.7241    0.8400        29
           2     1.0000    0.9231    0.9600        13

    accuracy                         0.9159       107
   macro avg     0.9595    0.8824    0.9118       107
weighted avg     0.9261    0.9159    0.9124       107



In [ ]:
#оценка метода деревья решений
print(classification_report(y_test, y_predict_tree, digits = 4))

              precision    recall  f1-score   support

           0     0.7391    0.7846    0.7612        65
           1     0.5385    0.4828    0.5091        29
           2     0.7500    0.6923    0.7200        13

    accuracy                         0.6916       107
   macro avg     0.6759    0.6532    0.6634       107
weighted avg     0.6861    0.6916    0.6879       107



In [ ]:
#оценка метода случайный лес
print(classification_report(y_test, y_predict_random_forest, digits = 4))

              precision    recall  f1-score   support

           0     0.7391    0.7846    0.7612        65
           1     0.5385    0.4828    0.5091        29
           2     0.7500    0.6923    0.7200        13

    accuracy                         0.6916       107
   macro avg     0.6759    0.6532    0.6634       107
weighted avg     0.6861    0.6916    0.6879       107



In [ ]:
#оценка метода K-ближайших соседей
print(classification_report(y_test, y_predict_knn, digits = 4))

              precision    recall  f1-score   support

           0     0.7391    0.7846    0.7612        65
           1     0.5385    0.4828    0.5091        29
           2     0.7500    0.6923    0.7200        13

    accuracy                         0.6916       107
   macro avg     0.6759    0.6532    0.6634       107
weighted avg     0.6861    0.6916    0.6879       107



Выбрать наилучший классификатор.
Исходя из оценки разных метрдов, лучшим классификатором оказался метод опорных векторов. На втором месте метод линейной регрессии, что не удивительно, так как в обоих методах используется разделяющяя гиперплоскость. Оставшиеся методы выдали одинаковый результат, который оказался худшим.

Наилучший классификатор: Метод опорных векторов.  

